apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lamp-helm-chart.fullname" . }}
  labels:
    {{- include "lamp-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lamp-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lamp-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "lamp-helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-php
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MYSQL_HOST
            value: {{ $.Values.externalDatabase.host | quote }}
          - name: MYSQL_PORT
            value: {{ $.Values.externalDatabase.port | quote }}
          - name: MYSQL_DATABASE
            value: {{ $.Values.externalDatabase.database | quote }}
          - name: MYSQL_USER
            value: {{ $.Values.externalDatabase.user | quote }}
          - name: MYSQL_PASSWORD
            value: {{ $.Values.externalDatabase.password | quote }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
{{ toYaml .Values.php.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
