{{- if .Values.externalSecrets.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    app: "{{ template "wordpress.fullname" . }}"
    chart: "{{ template "wordpress.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
secretDescriptor:
  backendType: {{ .Values.externalSecrets.backendType }}
  data:
  {{- range $key, $value := .Values.externalSecrets.mapping }}
    - key: {{ $value }}
      name: {{ $key }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    app: "{{ template "wordpress.fullname" . }}"
    chart: "{{ template "wordpress.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  wordpress-username: {{ default "" .Values.wordpressUsername | b64enc | quote }}
  {{- if .Values.wordpressPassword }}
  wordpress-password: {{ default "" .Values.wordpressPassword | b64enc | quote }}
  {{- else }}
  wordpress-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  db-username: {{ .Values.externalDatabase.user | b64enc | quote }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- if .Values.externalDatabase.root_user }}
  db-root-username: {{ .Values.externalDatabase.root_user | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalDatabase.root_password }}
  db-root-password: {{ .Values.externalDatabase.root_password | b64enc | quote }}
  {{- end }}
{{- end }}
