{{- if .Values.externalSecrets.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ template "lamp.fullname" . }}
  labels:
    app: "{{ template "lamp.fullname" . }}"
    chart: "{{ template "lamp.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
secretDescriptor:
  backendType: {{ .Values.externalSecrets.backendType }}
  data:
  {{- range $key, $value := .Values.externalSecrets.mapping }}
    - key: {{ $value }}
      name: {{ $key }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lamp.fullname" . }}
  labels:
    app: "{{ template "lamp.fullname" . }}"
    chart: "{{ template "lamp.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
#ENV DB_HOST=
#ENV DB_PORT=
#ENV DB_USER=
#ENV DB_PASSWORD=
#ENV DB_DATABASE=
  db-host: {{ .Values.dbHost | b64enc | quote }}
  db-port: {{ .Values.dbPort | b64enc | quote }}
  db-user: {{ .Values.dbUser | b64enc | quote }}
  db-password: {{ .Values.dbPassword | b64enc | quote }}
  db-database: {{ .Values.dbDatabase | b64enc | quote }}
{{- end }}

